name: Test Preprocessing Script

on:
  workflow_dispatch:

jobs:
  test-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: |
          python preprocessing_script.py
          
      - name: Split Data
        run: |
          python data_split.py

      - name: Upload cleaned output
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-data
          path: data/preprocessed_copyrights.csv

      - name: Upload Split Data
        uses: actions/upload-artifact@v4
        with:
          name: split-data
          path: |
            data/train_data.csv
            data/test_data.csv
